/* This file was generated by SableCC (http://www.sablecc.org/). */

package cardlang.node;

import cardlang.analysis.*;

@SuppressWarnings("nls")
public final class AAndLogicalopt extends PLogicalopt
{
    private TKwand _kwand_;

    public AAndLogicalopt()
    {
        // Constructor
    }

    public AAndLogicalopt(
        @SuppressWarnings("hiding") TKwand _kwand_)
    {
        // Constructor
        setKwand(_kwand_);

    }

    @Override
    public Object clone()
    {
        return new AAndLogicalopt(
            cloneNode(this._kwand_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAndLogicalopt(this);
    }

    public TKwand getKwand()
    {
        return this._kwand_;
    }

    public void setKwand(TKwand node)
    {
        if(this._kwand_ != null)
        {
            this._kwand_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._kwand_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._kwand_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._kwand_ == child)
        {
            this._kwand_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._kwand_ == oldChild)
        {
            setKwand((TKwand) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
