/* This file was generated by SableCC (http://www.sablecc.org/). */

package cardlang.node;

import cardlang.analysis.*;

@SuppressWarnings("nls")
public final class ABaseBoolexpr extends PBoolexpr
{
    private PBoolobj _boolobj_;

    public ABaseBoolexpr()
    {
        // Constructor
    }

    public ABaseBoolexpr(
        @SuppressWarnings("hiding") PBoolobj _boolobj_)
    {
        // Constructor
        setBoolobj(_boolobj_);

    }

    @Override
    public Object clone()
    {
        return new ABaseBoolexpr(
            cloneNode(this._boolobj_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABaseBoolexpr(this);
    }

    public PBoolobj getBoolobj()
    {
        return this._boolobj_;
    }

    public void setBoolobj(PBoolobj node)
    {
        if(this._boolobj_ != null)
        {
            this._boolobj_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._boolobj_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._boolobj_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._boolobj_ == child)
        {
            this._boolobj_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._boolobj_ == oldChild)
        {
            setBoolobj((PBoolobj) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
