/* This file was generated by SableCC (http://www.sablecc.org/). */

package cardlang.node;

import cardlang.analysis.*;

@SuppressWarnings("nls")
public final class ABaseShift extends PShift
{
    private PObj _obj_;
    private TOptshift _optshift_;
    private PExpr _expr_;

    public ABaseShift()
    {
        // Constructor
    }

    public ABaseShift(
        @SuppressWarnings("hiding") PObj _obj_,
        @SuppressWarnings("hiding") TOptshift _optshift_,
        @SuppressWarnings("hiding") PExpr _expr_)
    {
        // Constructor
        setObj(_obj_);

        setOptshift(_optshift_);

        setExpr(_expr_);

    }

    @Override
    public Object clone()
    {
        return new ABaseShift(
            cloneNode(this._obj_),
            cloneNode(this._optshift_),
            cloneNode(this._expr_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABaseShift(this);
    }

    public PObj getObj()
    {
        return this._obj_;
    }

    public void setObj(PObj node)
    {
        if(this._obj_ != null)
        {
            this._obj_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._obj_ = node;
    }

    public TOptshift getOptshift()
    {
        return this._optshift_;
    }

    public void setOptshift(TOptshift node)
    {
        if(this._optshift_ != null)
        {
            this._optshift_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._optshift_ = node;
    }

    public PExpr getExpr()
    {
        return this._expr_;
    }

    public void setExpr(PExpr node)
    {
        if(this._expr_ != null)
        {
            this._expr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expr_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._obj_)
            + toString(this._optshift_)
            + toString(this._expr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._obj_ == child)
        {
            this._obj_ = null;
            return;
        }

        if(this._optshift_ == child)
        {
            this._optshift_ = null;
            return;
        }

        if(this._expr_ == child)
        {
            this._expr_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._obj_ == oldChild)
        {
            setObj((PObj) newChild);
            return;
        }

        if(this._optshift_ == oldChild)
        {
            setOptshift((TOptshift) newChild);
            return;
        }

        if(this._expr_ == oldChild)
        {
            setExpr((PExpr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
