/* This file was generated by SableCC (http://www.sablecc.org/). */

package cardlang.node;

import cardlang.analysis.*;

@SuppressWarnings("nls")
public final class AContinueStmt extends PStmt
{
    private TKwcontinue _kwcontinue_;

    public AContinueStmt()
    {
        // Constructor
    }

    public AContinueStmt(
        @SuppressWarnings("hiding") TKwcontinue _kwcontinue_)
    {
        // Constructor
        setKwcontinue(_kwcontinue_);

    }

    @Override
    public Object clone()
    {
        return new AContinueStmt(
            cloneNode(this._kwcontinue_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAContinueStmt(this);
    }

    public TKwcontinue getKwcontinue()
    {
        return this._kwcontinue_;
    }

    public void setKwcontinue(TKwcontinue node)
    {
        if(this._kwcontinue_ != null)
        {
            this._kwcontinue_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._kwcontinue_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._kwcontinue_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._kwcontinue_ == child)
        {
            this._kwcontinue_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._kwcontinue_ == oldChild)
        {
            setKwcontinue((TKwcontinue) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
