/* This file was generated by SableCC (http://www.sablecc.org/). */

package cardlang.node;

import cardlang.analysis.*;

@SuppressWarnings("nls")
public final class ADivNumopt extends PNumopt
{
    private TOptdiv _optdiv_;

    public ADivNumopt()
    {
        // Constructor
    }

    public ADivNumopt(
        @SuppressWarnings("hiding") TOptdiv _optdiv_)
    {
        // Constructor
        setOptdiv(_optdiv_);

    }

    @Override
    public Object clone()
    {
        return new ADivNumopt(
            cloneNode(this._optdiv_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADivNumopt(this);
    }

    public TOptdiv getOptdiv()
    {
        return this._optdiv_;
    }

    public void setOptdiv(TOptdiv node)
    {
        if(this._optdiv_ != null)
        {
            this._optdiv_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._optdiv_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._optdiv_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._optdiv_ == child)
        {
            this._optdiv_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._optdiv_ == oldChild)
        {
            setOptdiv((TOptdiv) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
