/* This file was generated by SableCC (http://www.sablecc.org/). */

package cardlang.node;

import cardlang.analysis.*;

@SuppressWarnings("nls")
public final class AEqualCompopt extends PCompopt
{
    private TOptequal _optequal_;

    public AEqualCompopt()
    {
        // Constructor
    }

    public AEqualCompopt(
        @SuppressWarnings("hiding") TOptequal _optequal_)
    {
        // Constructor
        setOptequal(_optequal_);

    }

    @Override
    public Object clone()
    {
        return new AEqualCompopt(
            cloneNode(this._optequal_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEqualCompopt(this);
    }

    public TOptequal getOptequal()
    {
        return this._optequal_;
    }

    public void setOptequal(TOptequal node)
    {
        if(this._optequal_ != null)
        {
            this._optequal_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._optequal_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._optequal_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._optequal_ == child)
        {
            this._optequal_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._optequal_ == oldChild)
        {
            setOptequal((TOptequal) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
