/* This file was generated by SableCC (http://www.sablecc.org/). */

package cardlang.node;

import cardlang.analysis.*;

@SuppressWarnings("nls")
public final class AForStmt extends PStmt
{
    private PFor _for_;

    public AForStmt()
    {
        // Constructor
    }

    public AForStmt(
        @SuppressWarnings("hiding") PFor _for_)
    {
        // Constructor
        setFor(_for_);

    }

    @Override
    public Object clone()
    {
        return new AForStmt(
            cloneNode(this._for_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAForStmt(this);
    }

    public PFor getFor()
    {
        return this._for_;
    }

    public void setFor(PFor node)
    {
        if(this._for_ != null)
        {
            this._for_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._for_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._for_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._for_ == child)
        {
            this._for_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._for_ == oldChild)
        {
            setFor((PFor) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
