/* This file was generated by SableCC (http://www.sablecc.org/). */

package cardlang.node;

import cardlang.analysis.*;

@SuppressWarnings("nls")
public final class AGame extends PGame
{
    private TKwgame _kwgame_;
    private TLiteral _literal_;
    private PStmtblock _stmtblock_;

    public AGame()
    {
        // Constructor
    }

    public AGame(
        @SuppressWarnings("hiding") TKwgame _kwgame_,
        @SuppressWarnings("hiding") TLiteral _literal_,
        @SuppressWarnings("hiding") PStmtblock _stmtblock_)
    {
        // Constructor
        setKwgame(_kwgame_);

        setLiteral(_literal_);

        setStmtblock(_stmtblock_);

    }

    @Override
    public Object clone()
    {
        return new AGame(
            cloneNode(this._kwgame_),
            cloneNode(this._literal_),
            cloneNode(this._stmtblock_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAGame(this);
    }

    public TKwgame getKwgame()
    {
        return this._kwgame_;
    }

    public void setKwgame(TKwgame node)
    {
        if(this._kwgame_ != null)
        {
            this._kwgame_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._kwgame_ = node;
    }

    public TLiteral getLiteral()
    {
        return this._literal_;
    }

    public void setLiteral(TLiteral node)
    {
        if(this._literal_ != null)
        {
            this._literal_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._literal_ = node;
    }

    public PStmtblock getStmtblock()
    {
        return this._stmtblock_;
    }

    public void setStmtblock(PStmtblock node)
    {
        if(this._stmtblock_ != null)
        {
            this._stmtblock_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._stmtblock_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._kwgame_)
            + toString(this._literal_)
            + toString(this._stmtblock_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._kwgame_ == child)
        {
            this._kwgame_ = null;
            return;
        }

        if(this._literal_ == child)
        {
            this._literal_ = null;
            return;
        }

        if(this._stmtblock_ == child)
        {
            this._stmtblock_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._kwgame_ == oldChild)
        {
            setKwgame((TKwgame) newChild);
            return;
        }

        if(this._literal_ == oldChild)
        {
            setLiteral((TLiteral) newChild);
            return;
        }

        if(this._stmtblock_ == oldChild)
        {
            setStmtblock((PStmtblock) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
