/* This file was generated by SableCC (http://www.sablecc.org/). */

package cardlang.node;

import cardlang.analysis.*;

@SuppressWarnings("nls")
public final class AInequalCompopt extends PCompopt
{
    private TOptinequal _optinequal_;

    public AInequalCompopt()
    {
        // Constructor
    }

    public AInequalCompopt(
        @SuppressWarnings("hiding") TOptinequal _optinequal_)
    {
        // Constructor
        setOptinequal(_optinequal_);

    }

    @Override
    public Object clone()
    {
        return new AInequalCompopt(
            cloneNode(this._optinequal_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAInequalCompopt(this);
    }

    public TOptinequal getOptinequal()
    {
        return this._optinequal_;
    }

    public void setOptinequal(TOptinequal node)
    {
        if(this._optinequal_ != null)
        {
            this._optinequal_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._optinequal_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._optinequal_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._optinequal_ == child)
        {
            this._optinequal_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._optinequal_ == oldChild)
        {
            setOptinequal((TOptinequal) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
