/* This file was generated by SableCC (http://www.sablecc.org/). */

package cardlang.node;

import cardlang.analysis.*;

@SuppressWarnings("nls")
public final class ALargerequalCompexpr extends PCompexpr
{
    private PNumexpr _lexpr_;
    private TOptlargerequal _optlargerequal_;
    private PNumexpr _rexpr_;

    public ALargerequalCompexpr()
    {
        // Constructor
    }

    public ALargerequalCompexpr(
        @SuppressWarnings("hiding") PNumexpr _lexpr_,
        @SuppressWarnings("hiding") TOptlargerequal _optlargerequal_,
        @SuppressWarnings("hiding") PNumexpr _rexpr_)
    {
        // Constructor
        setLexpr(_lexpr_);

        setOptlargerequal(_optlargerequal_);

        setRexpr(_rexpr_);

    }

    @Override
    public Object clone()
    {
        return new ALargerequalCompexpr(
            cloneNode(this._lexpr_),
            cloneNode(this._optlargerequal_),
            cloneNode(this._rexpr_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALargerequalCompexpr(this);
    }

    public PNumexpr getLexpr()
    {
        return this._lexpr_;
    }

    public void setLexpr(PNumexpr node)
    {
        if(this._lexpr_ != null)
        {
            this._lexpr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lexpr_ = node;
    }

    public TOptlargerequal getOptlargerequal()
    {
        return this._optlargerequal_;
    }

    public void setOptlargerequal(TOptlargerequal node)
    {
        if(this._optlargerequal_ != null)
        {
            this._optlargerequal_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._optlargerequal_ = node;
    }

    public PNumexpr getRexpr()
    {
        return this._rexpr_;
    }

    public void setRexpr(PNumexpr node)
    {
        if(this._rexpr_ != null)
        {
            this._rexpr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._rexpr_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._lexpr_)
            + toString(this._optlargerequal_)
            + toString(this._rexpr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._lexpr_ == child)
        {
            this._lexpr_ = null;
            return;
        }

        if(this._optlargerequal_ == child)
        {
            this._optlargerequal_ = null;
            return;
        }

        if(this._rexpr_ == child)
        {
            this._rexpr_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._lexpr_ == oldChild)
        {
            setLexpr((PNumexpr) newChild);
            return;
        }

        if(this._optlargerequal_ == oldChild)
        {
            setOptlargerequal((TOptlargerequal) newChild);
            return;
        }

        if(this._rexpr_ == oldChild)
        {
            setRexpr((PNumexpr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
