/* This file was generated by SableCC (http://www.sablecc.org/). */

package cardlang.node;

import cardlang.analysis.*;

@SuppressWarnings("nls")
public final class ALargerequalCompopt extends PCompopt
{
    private TOptlargerequal _optlargerequal_;

    public ALargerequalCompopt()
    {
        // Constructor
    }

    public ALargerequalCompopt(
        @SuppressWarnings("hiding") TOptlargerequal _optlargerequal_)
    {
        // Constructor
        setOptlargerequal(_optlargerequal_);

    }

    @Override
    public Object clone()
    {
        return new ALargerequalCompopt(
            cloneNode(this._optlargerequal_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALargerequalCompopt(this);
    }

    public TOptlargerequal getOptlargerequal()
    {
        return this._optlargerequal_;
    }

    public void setOptlargerequal(TOptlargerequal node)
    {
        if(this._optlargerequal_ != null)
        {
            this._optlargerequal_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._optlargerequal_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._optlargerequal_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._optlargerequal_ == child)
        {
            this._optlargerequal_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._optlargerequal_ == oldChild)
        {
            setOptlargerequal((TOptlargerequal) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
