/* This file was generated by SableCC (http://www.sablecc.org/). */

package cardlang.node;

import cardlang.analysis.*;

@SuppressWarnings("nls")
public final class ALessequalCompexpr extends PCompexpr
{
    private PNumexpr _lexpr_;
    private TOptlessequal _optlessequal_;
    private PNumexpr _rexpr_;

    public ALessequalCompexpr()
    {
        // Constructor
    }

    public ALessequalCompexpr(
        @SuppressWarnings("hiding") PNumexpr _lexpr_,
        @SuppressWarnings("hiding") TOptlessequal _optlessequal_,
        @SuppressWarnings("hiding") PNumexpr _rexpr_)
    {
        // Constructor
        setLexpr(_lexpr_);

        setOptlessequal(_optlessequal_);

        setRexpr(_rexpr_);

    }

    @Override
    public Object clone()
    {
        return new ALessequalCompexpr(
            cloneNode(this._lexpr_),
            cloneNode(this._optlessequal_),
            cloneNode(this._rexpr_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALessequalCompexpr(this);
    }

    public PNumexpr getLexpr()
    {
        return this._lexpr_;
    }

    public void setLexpr(PNumexpr node)
    {
        if(this._lexpr_ != null)
        {
            this._lexpr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lexpr_ = node;
    }

    public TOptlessequal getOptlessequal()
    {
        return this._optlessequal_;
    }

    public void setOptlessequal(TOptlessequal node)
    {
        if(this._optlessequal_ != null)
        {
            this._optlessequal_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._optlessequal_ = node;
    }

    public PNumexpr getRexpr()
    {
        return this._rexpr_;
    }

    public void setRexpr(PNumexpr node)
    {
        if(this._rexpr_ != null)
        {
            this._rexpr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._rexpr_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._lexpr_)
            + toString(this._optlessequal_)
            + toString(this._rexpr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._lexpr_ == child)
        {
            this._lexpr_ = null;
            return;
        }

        if(this._optlessequal_ == child)
        {
            this._optlessequal_ = null;
            return;
        }

        if(this._rexpr_ == child)
        {
            this._rexpr_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._lexpr_ == oldChild)
        {
            setLexpr((PNumexpr) newChild);
            return;
        }

        if(this._optlessequal_ == oldChild)
        {
            setOptlessequal((TOptlessequal) newChild);
            return;
        }

        if(this._rexpr_ == oldChild)
        {
            setRexpr((PNumexpr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
