/* This file was generated by SableCC (http://www.sablecc.org/). */

package cardlang.node;

import cardlang.analysis.*;

@SuppressWarnings("nls")
public final class AMinusNumopt extends PNumopt
{
    private TOptminus _optminus_;

    public AMinusNumopt()
    {
        // Constructor
    }

    public AMinusNumopt(
        @SuppressWarnings("hiding") TOptminus _optminus_)
    {
        // Constructor
        setOptminus(_optminus_);

    }

    @Override
    public Object clone()
    {
        return new AMinusNumopt(
            cloneNode(this._optminus_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMinusNumopt(this);
    }

    public TOptminus getOptminus()
    {
        return this._optminus_;
    }

    public void setOptminus(TOptminus node)
    {
        if(this._optminus_ != null)
        {
            this._optminus_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._optminus_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._optminus_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._optminus_ == child)
        {
            this._optminus_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._optminus_ == oldChild)
        {
            setOptminus((TOptminus) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
