/* This file was generated by SableCC (http://www.sablecc.org/). */

package cardlang.node;

import cardlang.analysis.*;

@SuppressWarnings("nls")
public final class AModNumopt extends PNumopt
{
    private TOptmod _optmod_;

    public AModNumopt()
    {
        // Constructor
    }

    public AModNumopt(
        @SuppressWarnings("hiding") TOptmod _optmod_)
    {
        // Constructor
        setOptmod(_optmod_);

    }

    @Override
    public Object clone()
    {
        return new AModNumopt(
            cloneNode(this._optmod_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAModNumopt(this);
    }

    public TOptmod getOptmod()
    {
        return this._optmod_;
    }

    public void setOptmod(TOptmod node)
    {
        if(this._optmod_ != null)
        {
            this._optmod_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._optmod_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._optmod_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._optmod_ == child)
        {
            this._optmod_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._optmod_ == oldChild)
        {
            setOptmod((TOptmod) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
