/* This file was generated by SableCC (http://www.sablecc.org/). */

package cardlang.node;

import cardlang.analysis.*;

@SuppressWarnings("nls")
public final class AMultiNumopt extends PNumopt
{
    private TOptmulti _optmulti_;

    public AMultiNumopt()
    {
        // Constructor
    }

    public AMultiNumopt(
        @SuppressWarnings("hiding") TOptmulti _optmulti_)
    {
        // Constructor
        setOptmulti(_optmulti_);

    }

    @Override
    public Object clone()
    {
        return new AMultiNumopt(
            cloneNode(this._optmulti_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMultiNumopt(this);
    }

    public TOptmulti getOptmulti()
    {
        return this._optmulti_;
    }

    public void setOptmulti(TOptmulti node)
    {
        if(this._optmulti_ != null)
        {
            this._optmulti_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._optmulti_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._optmulti_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._optmulti_ == child)
        {
            this._optmulti_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._optmulti_ == oldChild)
        {
            setOptmulti((TOptmulti) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
