/* This file was generated by SableCC (http://www.sablecc.org/). */

package cardlang.node;

import cardlang.analysis.*;

@SuppressWarnings("nls")
public final class ANextidId extends PId
{
    private TKwnextid _kwnextid_;

    public ANextidId()
    {
        // Constructor
    }

    public ANextidId(
        @SuppressWarnings("hiding") TKwnextid _kwnextid_)
    {
        // Constructor
        setKwnextid(_kwnextid_);

    }

    @Override
    public Object clone()
    {
        return new ANextidId(
            cloneNode(this._kwnextid_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANextidId(this);
    }

    public TKwnextid getKwnextid()
    {
        return this._kwnextid_;
    }

    public void setKwnextid(TKwnextid node)
    {
        if(this._kwnextid_ != null)
        {
            this._kwnextid_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._kwnextid_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._kwnextid_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._kwnextid_ == child)
        {
            this._kwnextid_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._kwnextid_ == oldChild)
        {
            setKwnextid((TKwnextid) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
