/* This file was generated by SableCC (http://www.sablecc.org/). */

package cardlang.node;

import cardlang.analysis.*;

@SuppressWarnings("nls")
public final class ANextid extends PNextid
{
    private TKwnextid _kwnextid_;
    private PStmtblock _stmtblock_;

    public ANextid()
    {
        // Constructor
    }

    public ANextid(
        @SuppressWarnings("hiding") TKwnextid _kwnextid_,
        @SuppressWarnings("hiding") PStmtblock _stmtblock_)
    {
        // Constructor
        setKwnextid(_kwnextid_);

        setStmtblock(_stmtblock_);

    }

    @Override
    public Object clone()
    {
        return new ANextid(
            cloneNode(this._kwnextid_),
            cloneNode(this._stmtblock_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANextid(this);
    }

    public TKwnextid getKwnextid()
    {
        return this._kwnextid_;
    }

    public void setKwnextid(TKwnextid node)
    {
        if(this._kwnextid_ != null)
        {
            this._kwnextid_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._kwnextid_ = node;
    }

    public PStmtblock getStmtblock()
    {
        return this._stmtblock_;
    }

    public void setStmtblock(PStmtblock node)
    {
        if(this._stmtblock_ != null)
        {
            this._stmtblock_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._stmtblock_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._kwnextid_)
            + toString(this._stmtblock_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._kwnextid_ == child)
        {
            this._kwnextid_ = null;
            return;
        }

        if(this._stmtblock_ == child)
        {
            this._stmtblock_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._kwnextid_ == oldChild)
        {
            setKwnextid((TKwnextid) newChild);
            return;
        }

        if(this._stmtblock_ == oldChild)
        {
            setStmtblock((PStmtblock) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
