/* This file was generated by SableCC (http://www.sablecc.org/). */

package cardlang.node;

import cardlang.analysis.*;

@SuppressWarnings("nls")
public final class ANotBoolobj extends PBoolobj
{
    private TKwnot _kwnot_;
    private PBoolobj _boolobj_;

    public ANotBoolobj()
    {
        // Constructor
    }

    public ANotBoolobj(
        @SuppressWarnings("hiding") TKwnot _kwnot_,
        @SuppressWarnings("hiding") PBoolobj _boolobj_)
    {
        // Constructor
        setKwnot(_kwnot_);

        setBoolobj(_boolobj_);

    }

    @Override
    public Object clone()
    {
        return new ANotBoolobj(
            cloneNode(this._kwnot_),
            cloneNode(this._boolobj_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANotBoolobj(this);
    }

    public TKwnot getKwnot()
    {
        return this._kwnot_;
    }

    public void setKwnot(TKwnot node)
    {
        if(this._kwnot_ != null)
        {
            this._kwnot_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._kwnot_ = node;
    }

    public PBoolobj getBoolobj()
    {
        return this._boolobj_;
    }

    public void setBoolobj(PBoolobj node)
    {
        if(this._boolobj_ != null)
        {
            this._boolobj_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._boolobj_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._kwnot_)
            + toString(this._boolobj_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._kwnot_ == child)
        {
            this._kwnot_ = null;
            return;
        }

        if(this._boolobj_ == child)
        {
            this._boolobj_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._kwnot_ == oldChild)
        {
            setKwnot((TKwnot) newChild);
            return;
        }

        if(this._boolobj_ == oldChild)
        {
            setBoolobj((PBoolobj) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
