/* This file was generated by SableCC (http://www.sablecc.org/). */

package cardlang.node;

import cardlang.analysis.*;

@SuppressWarnings("nls")
public final class ANotFactor extends PFactor
{
    private TKwnot _kwnot_;
    private PCompexpr _compexpr_;

    public ANotFactor()
    {
        // Constructor
    }

    public ANotFactor(
        @SuppressWarnings("hiding") TKwnot _kwnot_,
        @SuppressWarnings("hiding") PCompexpr _compexpr_)
    {
        // Constructor
        setKwnot(_kwnot_);

        setCompexpr(_compexpr_);

    }

    @Override
    public Object clone()
    {
        return new ANotFactor(
            cloneNode(this._kwnot_),
            cloneNode(this._compexpr_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANotFactor(this);
    }

    public TKwnot getKwnot()
    {
        return this._kwnot_;
    }

    public void setKwnot(TKwnot node)
    {
        if(this._kwnot_ != null)
        {
            this._kwnot_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._kwnot_ = node;
    }

    public PCompexpr getCompexpr()
    {
        return this._compexpr_;
    }

    public void setCompexpr(PCompexpr node)
    {
        if(this._compexpr_ != null)
        {
            this._compexpr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._compexpr_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._kwnot_)
            + toString(this._compexpr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._kwnot_ == child)
        {
            this._kwnot_ = null;
            return;
        }

        if(this._compexpr_ == child)
        {
            this._compexpr_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._kwnot_ == oldChild)
        {
            setKwnot((TKwnot) newChild);
            return;
        }

        if(this._compexpr_ == oldChild)
        {
            setCompexpr((PCompexpr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
