/* This file was generated by SableCC (http://www.sablecc.org/). */

package cardlang.node;

import cardlang.analysis.*;

@SuppressWarnings("nls")
public final class AObjVal extends PVal
{
    private PObj _obj_;

    public AObjVal()
    {
        // Constructor
    }

    public AObjVal(
        @SuppressWarnings("hiding") PObj _obj_)
    {
        // Constructor
        setObj(_obj_);

    }

    @Override
    public Object clone()
    {
        return new AObjVal(
            cloneNode(this._obj_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAObjVal(this);
    }

    public PObj getObj()
    {
        return this._obj_;
    }

    public void setObj(PObj node)
    {
        if(this._obj_ != null)
        {
            this._obj_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._obj_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._obj_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._obj_ == child)
        {
            this._obj_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._obj_ == oldChild)
        {
            setObj((PObj) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
