/* This file was generated by SableCC (http://www.sablecc.org/). */

package cardlang.node;

import cardlang.analysis.*;

@SuppressWarnings("nls")
public final class AOrLogicalopt extends PLogicalopt
{
    private TKwor _kwor_;

    public AOrLogicalopt()
    {
        // Constructor
    }

    public AOrLogicalopt(
        @SuppressWarnings("hiding") TKwor _kwor_)
    {
        // Constructor
        setKwor(_kwor_);

    }

    @Override
    public Object clone()
    {
        return new AOrLogicalopt(
            cloneNode(this._kwor_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOrLogicalopt(this);
    }

    public TKwor getKwor()
    {
        return this._kwor_;
    }

    public void setKwor(TKwor node)
    {
        if(this._kwor_ != null)
        {
            this._kwor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._kwor_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._kwor_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._kwor_ == child)
        {
            this._kwor_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._kwor_ == oldChild)
        {
            setKwor((TKwor) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
