/* This file was generated by SableCC (http://www.sablecc.org/). */

package cardlang.node;

import cardlang.analysis.*;

@SuppressWarnings("nls")
public final class AParenVal extends PVal
{
    private TLeftparen _leftparen_;
    private PExpr _expr_;
    private TRightparen _rightparen_;

    public AParenVal()
    {
        // Constructor
    }

    public AParenVal(
        @SuppressWarnings("hiding") TLeftparen _leftparen_,
        @SuppressWarnings("hiding") PExpr _expr_,
        @SuppressWarnings("hiding") TRightparen _rightparen_)
    {
        // Constructor
        setLeftparen(_leftparen_);

        setExpr(_expr_);

        setRightparen(_rightparen_);

    }

    @Override
    public Object clone()
    {
        return new AParenVal(
            cloneNode(this._leftparen_),
            cloneNode(this._expr_),
            cloneNode(this._rightparen_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAParenVal(this);
    }

    public TLeftparen getLeftparen()
    {
        return this._leftparen_;
    }

    public void setLeftparen(TLeftparen node)
    {
        if(this._leftparen_ != null)
        {
            this._leftparen_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._leftparen_ = node;
    }

    public PExpr getExpr()
    {
        return this._expr_;
    }

    public void setExpr(PExpr node)
    {
        if(this._expr_ != null)
        {
            this._expr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expr_ = node;
    }

    public TRightparen getRightparen()
    {
        return this._rightparen_;
    }

    public void setRightparen(TRightparen node)
    {
        if(this._rightparen_ != null)
        {
            this._rightparen_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._rightparen_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._leftparen_)
            + toString(this._expr_)
            + toString(this._rightparen_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._leftparen_ == child)
        {
            this._leftparen_ = null;
            return;
        }

        if(this._expr_ == child)
        {
            this._expr_ = null;
            return;
        }

        if(this._rightparen_ == child)
        {
            this._rightparen_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._leftparen_ == oldChild)
        {
            setLeftparen((TLeftparen) newChild);
            return;
        }

        if(this._expr_ == oldChild)
        {
            setExpr((PExpr) newChild);
            return;
        }

        if(this._rightparen_ == oldChild)
        {
            setRightparen((TRightparen) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
