/* This file was generated by SableCC (http://www.sablecc.org/). */

package cardlang.node;

import cardlang.analysis.*;

@SuppressWarnings("nls")
public final class APlusNumopt extends PNumopt
{
    private TOptplus _optplus_;

    public APlusNumopt()
    {
        // Constructor
    }

    public APlusNumopt(
        @SuppressWarnings("hiding") TOptplus _optplus_)
    {
        // Constructor
        setOptplus(_optplus_);

    }

    @Override
    public Object clone()
    {
        return new APlusNumopt(
            cloneNode(this._optplus_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPlusNumopt(this);
    }

    public TOptplus getOptplus()
    {
        return this._optplus_;
    }

    public void setOptplus(TOptplus node)
    {
        if(this._optplus_ != null)
        {
            this._optplus_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._optplus_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._optplus_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._optplus_ == child)
        {
            this._optplus_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._optplus_ == oldChild)
        {
            setOptplus((TOptplus) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
