/* This file was generated by SableCC (http://www.sablecc.org/). */

package cardlang.node;

import cardlang.analysis.*;

@SuppressWarnings("nls")
public final class ARecurShift extends PShift
{
    private PShift _shift_;
    private TOptshift _optshift_;
    private PExpr _expr_;

    public ARecurShift()
    {
        // Constructor
    }

    public ARecurShift(
        @SuppressWarnings("hiding") PShift _shift_,
        @SuppressWarnings("hiding") TOptshift _optshift_,
        @SuppressWarnings("hiding") PExpr _expr_)
    {
        // Constructor
        setShift(_shift_);

        setOptshift(_optshift_);

        setExpr(_expr_);

    }

    @Override
    public Object clone()
    {
        return new ARecurShift(
            cloneNode(this._shift_),
            cloneNode(this._optshift_),
            cloneNode(this._expr_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseARecurShift(this);
    }

    public PShift getShift()
    {
        return this._shift_;
    }

    public void setShift(PShift node)
    {
        if(this._shift_ != null)
        {
            this._shift_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._shift_ = node;
    }

    public TOptshift getOptshift()
    {
        return this._optshift_;
    }

    public void setOptshift(TOptshift node)
    {
        if(this._optshift_ != null)
        {
            this._optshift_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._optshift_ = node;
    }

    public PExpr getExpr()
    {
        return this._expr_;
    }

    public void setExpr(PExpr node)
    {
        if(this._expr_ != null)
        {
            this._expr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expr_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._shift_)
            + toString(this._optshift_)
            + toString(this._expr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._shift_ == child)
        {
            this._shift_ = null;
            return;
        }

        if(this._optshift_ == child)
        {
            this._optshift_ = null;
            return;
        }

        if(this._expr_ == child)
        {
            this._expr_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._shift_ == oldChild)
        {
            setShift((PShift) newChild);
            return;
        }

        if(this._optshift_ == oldChild)
        {
            setOptshift((TOptshift) newChild);
            return;
        }

        if(this._expr_ == oldChild)
        {
            setExpr((PExpr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
