/* This file was generated by SableCC (http://www.sablecc.org/). */

package cardlang.node;

import cardlang.analysis.*;

@SuppressWarnings("nls")
public final class ARecurBoolexpr extends PBoolexpr
{
    private PBoolexpr _boolexpr_;
    private PLogicalopt _logicalopt_;
    private PBoolobj _boolobj_;

    public ARecurBoolexpr()
    {
        // Constructor
    }

    public ARecurBoolexpr(
        @SuppressWarnings("hiding") PBoolexpr _boolexpr_,
        @SuppressWarnings("hiding") PLogicalopt _logicalopt_,
        @SuppressWarnings("hiding") PBoolobj _boolobj_)
    {
        // Constructor
        setBoolexpr(_boolexpr_);

        setLogicalopt(_logicalopt_);

        setBoolobj(_boolobj_);

    }

    @Override
    public Object clone()
    {
        return new ARecurBoolexpr(
            cloneNode(this._boolexpr_),
            cloneNode(this._logicalopt_),
            cloneNode(this._boolobj_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseARecurBoolexpr(this);
    }

    public PBoolexpr getBoolexpr()
    {
        return this._boolexpr_;
    }

    public void setBoolexpr(PBoolexpr node)
    {
        if(this._boolexpr_ != null)
        {
            this._boolexpr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._boolexpr_ = node;
    }

    public PLogicalopt getLogicalopt()
    {
        return this._logicalopt_;
    }

    public void setLogicalopt(PLogicalopt node)
    {
        if(this._logicalopt_ != null)
        {
            this._logicalopt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._logicalopt_ = node;
    }

    public PBoolobj getBoolobj()
    {
        return this._boolobj_;
    }

    public void setBoolobj(PBoolobj node)
    {
        if(this._boolobj_ != null)
        {
            this._boolobj_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._boolobj_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._boolexpr_)
            + toString(this._logicalopt_)
            + toString(this._boolobj_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._boolexpr_ == child)
        {
            this._boolexpr_ = null;
            return;
        }

        if(this._logicalopt_ == child)
        {
            this._logicalopt_ = null;
            return;
        }

        if(this._boolobj_ == child)
        {
            this._boolobj_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._boolexpr_ == oldChild)
        {
            setBoolexpr((PBoolexpr) newChild);
            return;
        }

        if(this._logicalopt_ == oldChild)
        {
            setLogicalopt((PLogicalopt) newChild);
            return;
        }

        if(this._boolobj_ == oldChild)
        {
            setBoolobj((PBoolobj) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
