/* This file was generated by SableCC (http://www.sablecc.org/). */

package cardlang.node;

import cardlang.analysis.*;

@SuppressWarnings("nls")
public final class AScreenId extends PId
{
    private TKwscreen _kwscreen_;

    public AScreenId()
    {
        // Constructor
    }

    public AScreenId(
        @SuppressWarnings("hiding") TKwscreen _kwscreen_)
    {
        // Constructor
        setKwscreen(_kwscreen_);

    }

    @Override
    public Object clone()
    {
        return new AScreenId(
            cloneNode(this._kwscreen_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAScreenId(this);
    }

    public TKwscreen getKwscreen()
    {
        return this._kwscreen_;
    }

    public void setKwscreen(TKwscreen node)
    {
        if(this._kwscreen_ != null)
        {
            this._kwscreen_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._kwscreen_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._kwscreen_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._kwscreen_ == child)
        {
            this._kwscreen_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._kwscreen_ == oldChild)
        {
            setKwscreen((TKwscreen) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
