/* This file was generated by SableCC (http://www.sablecc.org/). */

package cardlang.node;

import cardlang.analysis.*;

@SuppressWarnings("nls")
public final class AShiftStmt extends PStmt
{
    private PShift _shift_;

    public AShiftStmt()
    {
        // Constructor
    }

    public AShiftStmt(
        @SuppressWarnings("hiding") PShift _shift_)
    {
        // Constructor
        setShift(_shift_);

    }

    @Override
    public Object clone()
    {
        return new AShiftStmt(
            cloneNode(this._shift_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAShiftStmt(this);
    }

    public PShift getShift()
    {
        return this._shift_;
    }

    public void setShift(PShift node)
    {
        if(this._shift_ != null)
        {
            this._shift_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._shift_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._shift_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._shift_ == child)
        {
            this._shift_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._shift_ == oldChild)
        {
            setShift((PShift) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
