/* This file was generated by SableCC (http://www.sablecc.org/). */

package cardlang.node;

import java.util.*;
import cardlang.analysis.*;

@SuppressWarnings("nls")
public final class AStmtblock extends PStmtblock
{
    private TLeftbrace _leftbrace_;
    private final LinkedList<PStmt> _stmt_ = new LinkedList<PStmt>();
    private TRightbrace _rightbrace_;

    public AStmtblock()
    {
        // Constructor
    }

    public AStmtblock(
        @SuppressWarnings("hiding") TLeftbrace _leftbrace_,
        @SuppressWarnings("hiding") List<?> _stmt_,
        @SuppressWarnings("hiding") TRightbrace _rightbrace_)
    {
        // Constructor
        setLeftbrace(_leftbrace_);

        setStmt(_stmt_);

        setRightbrace(_rightbrace_);

    }

    @Override
    public Object clone()
    {
        return new AStmtblock(
            cloneNode(this._leftbrace_),
            cloneList(this._stmt_),
            cloneNode(this._rightbrace_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAStmtblock(this);
    }

    public TLeftbrace getLeftbrace()
    {
        return this._leftbrace_;
    }

    public void setLeftbrace(TLeftbrace node)
    {
        if(this._leftbrace_ != null)
        {
            this._leftbrace_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._leftbrace_ = node;
    }

    public LinkedList<PStmt> getStmt()
    {
        return this._stmt_;
    }

    public void setStmt(List<?> list)
    {
        for(PStmt e : this._stmt_)
        {
            e.parent(null);
        }
        this._stmt_.clear();

        for(Object obj_e : list)
        {
            PStmt e = (PStmt) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._stmt_.add(e);
        }
    }

    public TRightbrace getRightbrace()
    {
        return this._rightbrace_;
    }

    public void setRightbrace(TRightbrace node)
    {
        if(this._rightbrace_ != null)
        {
            this._rightbrace_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._rightbrace_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._leftbrace_)
            + toString(this._stmt_)
            + toString(this._rightbrace_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._leftbrace_ == child)
        {
            this._leftbrace_ = null;
            return;
        }

        if(this._stmt_.remove(child))
        {
            return;
        }

        if(this._rightbrace_ == child)
        {
            this._rightbrace_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._leftbrace_ == oldChild)
        {
            setLeftbrace((TLeftbrace) newChild);
            return;
        }

        for(ListIterator<PStmt> i = this._stmt_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PStmt) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(this._rightbrace_ == oldChild)
        {
            setRightbrace((TRightbrace) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
