/* This file was generated by SableCC (http://www.sablecc.org/). */

package cardlang.node;

import cardlang.analysis.*;

@SuppressWarnings("nls")
public final class ASubscriptObj extends PObj
{
    private PSubscript _subscript_;

    public ASubscriptObj()
    {
        // Constructor
    }

    public ASubscriptObj(
        @SuppressWarnings("hiding") PSubscript _subscript_)
    {
        // Constructor
        setSubscript(_subscript_);

    }

    @Override
    public Object clone()
    {
        return new ASubscriptObj(
            cloneNode(this._subscript_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASubscriptObj(this);
    }

    public PSubscript getSubscript()
    {
        return this._subscript_;
    }

    public void setSubscript(PSubscript node)
    {
        if(this._subscript_ != null)
        {
            this._subscript_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._subscript_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._subscript_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._subscript_ == child)
        {
            this._subscript_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._subscript_ == oldChild)
        {
            setSubscript((PSubscript) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
