/* This file was generated by SableCC (http://www.sablecc.org/). */

package cardlang.node;

import cardlang.analysis.*;

@SuppressWarnings("nls")
public final class AValidId extends PId
{
    private TKwvalid _kwvalid_;

    public AValidId()
    {
        // Constructor
    }

    public AValidId(
        @SuppressWarnings("hiding") TKwvalid _kwvalid_)
    {
        // Constructor
        setKwvalid(_kwvalid_);

    }

    @Override
    public Object clone()
    {
        return new AValidId(
            cloneNode(this._kwvalid_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAValidId(this);
    }

    public TKwvalid getKwvalid()
    {
        return this._kwvalid_;
    }

    public void setKwvalid(TKwvalid node)
    {
        if(this._kwvalid_ != null)
        {
            this._kwvalid_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._kwvalid_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._kwvalid_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._kwvalid_ == child)
        {
            this._kwvalid_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._kwvalid_ == oldChild)
        {
            setKwvalid((TKwvalid) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
