/* This file was generated by SableCC (http://www.sablecc.org/). */

package cardlang.node;

import cardlang.analysis.*;

@SuppressWarnings("nls")
public final class AValid extends PValid
{
    private TKwvalid _kwvalid_;
    private PStmtblock _stmtblock_;

    public AValid()
    {
        // Constructor
    }

    public AValid(
        @SuppressWarnings("hiding") TKwvalid _kwvalid_,
        @SuppressWarnings("hiding") PStmtblock _stmtblock_)
    {
        // Constructor
        setKwvalid(_kwvalid_);

        setStmtblock(_stmtblock_);

    }

    @Override
    public Object clone()
    {
        return new AValid(
            cloneNode(this._kwvalid_),
            cloneNode(this._stmtblock_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAValid(this);
    }

    public TKwvalid getKwvalid()
    {
        return this._kwvalid_;
    }

    public void setKwvalid(TKwvalid node)
    {
        if(this._kwvalid_ != null)
        {
            this._kwvalid_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._kwvalid_ = node;
    }

    public PStmtblock getStmtblock()
    {
        return this._stmtblock_;
    }

    public void setStmtblock(PStmtblock node)
    {
        if(this._stmtblock_ != null)
        {
            this._stmtblock_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._stmtblock_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._kwvalid_)
            + toString(this._stmtblock_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._kwvalid_ == child)
        {
            this._kwvalid_ = null;
            return;
        }

        if(this._stmtblock_ == child)
        {
            this._stmtblock_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._kwvalid_ == oldChild)
        {
            setKwvalid((TKwvalid) newChild);
            return;
        }

        if(this._stmtblock_ == oldChild)
        {
            setStmtblock((PStmtblock) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
