/* This file was generated by SableCC (http://www.sablecc.org/). */

package cardlang.node;

import cardlang.analysis.*;

@SuppressWarnings("nls")
public final class AWinnerid extends PWinnerid
{
    private TKwwinnerid _kwwinnerid_;
    private PStmtblock _stmtblock_;

    public AWinnerid()
    {
        // Constructor
    }

    public AWinnerid(
        @SuppressWarnings("hiding") TKwwinnerid _kwwinnerid_,
        @SuppressWarnings("hiding") PStmtblock _stmtblock_)
    {
        // Constructor
        setKwwinnerid(_kwwinnerid_);

        setStmtblock(_stmtblock_);

    }

    @Override
    public Object clone()
    {
        return new AWinnerid(
            cloneNode(this._kwwinnerid_),
            cloneNode(this._stmtblock_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAWinnerid(this);
    }

    public TKwwinnerid getKwwinnerid()
    {
        return this._kwwinnerid_;
    }

    public void setKwwinnerid(TKwwinnerid node)
    {
        if(this._kwwinnerid_ != null)
        {
            this._kwwinnerid_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._kwwinnerid_ = node;
    }

    public PStmtblock getStmtblock()
    {
        return this._stmtblock_;
    }

    public void setStmtblock(PStmtblock node)
    {
        if(this._stmtblock_ != null)
        {
            this._stmtblock_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._stmtblock_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._kwwinnerid_)
            + toString(this._stmtblock_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._kwwinnerid_ == child)
        {
            this._kwwinnerid_ = null;
            return;
        }

        if(this._stmtblock_ == child)
        {
            this._stmtblock_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._kwwinnerid_ == oldChild)
        {
            setKwwinnerid((TKwwinnerid) newChild);
            return;
        }

        if(this._stmtblock_ == oldChild)
        {
            setStmtblock((PStmtblock) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
