/* This file was generated by SableCC (http://www.sablecc.org/). */

package cardlang.node;

import cardlang.analysis.*;

@SuppressWarnings("nls")
public final class AWinneridId extends PId
{
    private TKwwinnerid _kwwinnerid_;

    public AWinneridId()
    {
        // Constructor
    }

    public AWinneridId(
        @SuppressWarnings("hiding") TKwwinnerid _kwwinnerid_)
    {
        // Constructor
        setKwwinnerid(_kwwinnerid_);

    }

    @Override
    public Object clone()
    {
        return new AWinneridId(
            cloneNode(this._kwwinnerid_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAWinneridId(this);
    }

    public TKwwinnerid getKwwinnerid()
    {
        return this._kwwinnerid_;
    }

    public void setKwwinnerid(TKwwinnerid node)
    {
        if(this._kwwinnerid_ != null)
        {
            this._kwwinnerid_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._kwwinnerid_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._kwwinnerid_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._kwwinnerid_ == child)
        {
            this._kwwinnerid_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._kwwinnerid_ == oldChild)
        {
            setKwwinnerid((TKwwinnerid) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
