/* This file was generated by SableCC (http://www.sablecc.org/). */

package cardlang.node;

import cardlang.analysis.*;

@SuppressWarnings("nls")
public final class TKwbreak extends Token
{
    public TKwbreak()
    {
        super.setText("Break");
    }

    public TKwbreak(int line, int pos)
    {
        super.setText("Break");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TKwbreak(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKwbreak(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKwbreak text.");
    }
}
