/* This file was generated by SableCC (http://www.sablecc.org/). */

package cardlang.node;

import cardlang.analysis.*;

@SuppressWarnings("nls")
public final class TKwcontinue extends Token
{
    public TKwcontinue()
    {
        super.setText("Continue");
    }

    public TKwcontinue(int line, int pos)
    {
        super.setText("Continue");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TKwcontinue(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKwcontinue(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKwcontinue text.");
    }
}
