/* This file was generated by SableCC (http://www.sablecc.org/). */

package cardlang.node;

import cardlang.analysis.*;

@SuppressWarnings("nls")
public final class TKwfrom extends Token
{
    public TKwfrom()
    {
        super.setText("From");
    }

    public TKwfrom(int line, int pos)
    {
        super.setText("From");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TKwfrom(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKwfrom(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKwfrom text.");
    }
}
