/* This file was generated by SableCC (http://www.sablecc.org/). */

package cardlang.node;

import cardlang.analysis.*;

@SuppressWarnings("nls")
public final class TKwfalse extends Token
{
    public TKwfalse()
    {
        super.setText("False");
    }

    public TKwfalse(int line, int pos)
    {
        super.setText("False");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TKwfalse(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKwfalse(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKwfalse text.");
    }
}
