/* This file was generated by SableCC (http://www.sablecc.org/). */

package cardlang.node;

import cardlang.analysis.*;

@SuppressWarnings("nls")
public final class TKwgame extends Token
{
    public TKwgame()
    {
        super.setText("Game");
    }

    public TKwgame(int line, int pos)
    {
        super.setText("Game");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TKwgame(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKwgame(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKwgame text.");
    }
}
