/* This file was generated by SableCC (http://www.sablecc.org/). */

package cardlang.node;

import cardlang.analysis.*;

@SuppressWarnings("nls")
public final class TKwnot extends Token
{
    public TKwnot()
    {
        super.setText("Not");
    }

    public TKwnot(int line, int pos)
    {
        super.setText("Not");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TKwnot(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKwnot(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKwnot text.");
    }
}
