/* This file was generated by SableCC (http://www.sablecc.org/). */

package cardlang.node;

import cardlang.analysis.*;

@SuppressWarnings("nls")
public final class TKwor extends Token
{
    public TKwor()
    {
        super.setText("Or");
    }

    public TKwor(int line, int pos)
    {
        super.setText("Or");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TKwor(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKwor(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKwor text.");
    }
}
