/* This file was generated by SableCC (http://www.sablecc.org/). */

package cardlang.node;

import cardlang.analysis.*;

@SuppressWarnings("nls")
public final class TKwtrue extends Token
{
    public TKwtrue()
    {
        super.setText("True");
    }

    public TKwtrue(int line, int pos)
    {
        super.setText("True");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TKwtrue(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKwtrue(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKwtrue text.");
    }
}
