/* This file was generated by SableCC (http://www.sablecc.org/). */

package cardlang.node;

import cardlang.analysis.*;

@SuppressWarnings("nls")
public final class TKwto extends Token
{
    public TKwto()
    {
        super.setText("To");
    }

    public TKwto(int line, int pos)
    {
        super.setText("To");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TKwto(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKwto(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKwto text.");
    }
}
