/* This file was generated by SableCC (http://www.sablecc.org/). */

package cardlang.node;

import cardlang.analysis.*;

@SuppressWarnings("nls")
public final class TKwvalid extends Token
{
    public TKwvalid()
    {
        super.setText("Valid");
    }

    public TKwvalid(int line, int pos)
    {
        super.setText("Valid");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TKwvalid(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKwvalid(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKwvalid text.");
    }
}
