/* This file was generated by SableCC (http://www.sablecc.org/). */

package cardlang.node;

import cardlang.analysis.*;

@SuppressWarnings("nls")
public final class TKwwinnerid extends Token
{
    public TKwwinnerid()
    {
        super.setText("WinnerID");
    }

    public TKwwinnerid(int line, int pos)
    {
        super.setText("WinnerID");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TKwwinnerid(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKwwinnerid(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKwwinnerid text.");
    }
}
