/* This file was generated by SableCC (http://www.sablecc.org/). */

package cardlang.node;

import cardlang.analysis.*;

@SuppressWarnings("nls")
public final class TKwwhile extends Token
{
    public TKwwhile()
    {
        super.setText("While");
    }

    public TKwwhile(int line, int pos)
    {
        super.setText("While");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TKwwhile(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKwwhile(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKwwhile text.");
    }
}
